version: "3.3"
services:
  sanva:
    build: .
    image: sanva
    container_name: sanva
    restart: unless-stopped
    environment:
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_ANON=$SUPABASE_ANON
      - TZ=Europe/Madrid
    ports:
      - 3000:3000
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.sanvalentin.entrypoints=websecure
      - traefik.http.routers.sanvalentin.rule=Host(`sanvalentin.$DOMAIN`)
      - traefik.http.routers.sanvalentin.tls=true
      - traefik.http.routers.sanvalentin.tls.certresolver=le


networks:
  traefik:
    name: traefik
    external: true
