version: "3.3"
services:
  sanva:
    build: .
    image: sanva
    container_name: sanva
    restart: unless-stopped
    volumes:
      - /tmp/prisma/data:/app/prisma/data
    ports:
      - 3000:3000
    # command: yarn prisma migrate dev --name init & yarn run start
    environment:
      - TZ=Europe/Madrid
